import NavBar from '@/components/NavBar'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col text-xl font-semibold space-y-6'>
        <h1 className='text-7xl font-thin text-center'>Hey bro.. Whassapppp..!!</h1>
       </main>
      
    </ div>
  )
}
